/** Accept only the embed URL generated by Google Maps' Share menu. */
export function isGoogleMapsEmbedUrl(value: string): boolean {
  try {
    const url = new URL(value);

    return (
      url.protocol === 'https:' &&
      url.hostname === 'www.google.com' &&
      url.port === '' &&
      url.username === '' &&
      url.password === '' &&
      url.pathname === '/maps/embed' &&
      Boolean(url.searchParams.get('pb')?.trim())
    );
  } catch {
    return false;
  }
}
