import { GlobalTransition } from '@/components/layout/GlobalTransition';
import { ModeProvider } from '@/components/providers/ModeProvider';
import { ThemeProvider } from '@/components/ui/theme-provider';
import { SiteMode, isSupportedMode } from '@/lib/preferences';
import type { Metadata } from 'next';
import { Cormorant_Garamond, Manrope, Sora } from 'next/font/google';
import { cookies } from 'next/headers';
import './globals.css';

// Sora supports Latin + Thai through fallback to system fonts
// For full Thai support, tailwind.config uses font-sans with Thai-capable system stack
const sora = Sora({
  variable: '--font-sora',
  subsets: ['latin', 'latin-ext'],
});

const cormorantGaramond = Cormorant_Garamond({
  variable: '--font-cormorant-garamond',
  subsets: ['latin', 'latin-ext'],
});

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin', 'latin-ext'],
});

export const metadata: Metadata = {
  title: '56KonFilm',
  description: 'Generated by create next app',
};

// Map mode to theme for initial server rendering
const MODE_TO_THEME: Record<SiteMode, string> = {
  production: 'dark',
  wedding: 'light',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  // Validate cookie value server-side
  const cookieValue = cookieStore.get('mode')?.value;
  const initialMode: SiteMode = isSupportedMode(cookieValue || '') 
    ? (cookieValue as SiteMode) 
    : 'production';
  const initialTheme = MODE_TO_THEME[initialMode];

  return (
    // data-mode helps with CSS selection, data-theme helps next-themes
    <html lang="en" suppressHydrationWarning data-mode={initialMode} style={{ colorScheme: initialTheme }}>
      <body
        className={`${sora.variable} ${cormorantGaramond.variable} ${manrope.variable} font-body antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme={initialTheme} // FORCE default theme based on server mode
          enableSystem={false} // Disable system preference to enforce mode-based theme
          disableTransitionOnChange
        >
          {/* Synchronize store with server state */}
          <ModeProvider initialMode={initialMode}>
            <GlobalTransition />
            {children}
          </ModeProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
