import { ModeProvider } from '@/components/providers/ModeProvider'; // Import wrapping provider
import { ThemeProvider } from '@/components/ui/theme-provider';
import { SiteMode } from '@/lib/preferences';
import type { Metadata } from 'next';
import { Cormorant_Garamond, Manrope, Sora } from 'next/font/google';
import { cookies } from 'next/headers';
import './globals.css';

const sora = Sora({
  variable: '--font-sora',
  subsets: ['latin'],
});

const cormorantGaramond = Cormorant_Garamond({
  variable: '--font-cormorant-garamond',
  subsets: ['latin'],
});

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: '56KonFilm',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Read initial mode from cookie, defaulting to 'production' if not found
  const cookieStore = await cookies();
  const initialMode = (cookieStore.get('mode')?.value as SiteMode) || 'production';

  return (
    // Add data-mode attribute for CSS variable selector matching
    <html lang="en" suppressHydrationWarning data-mode={initialMode}>
      <body
        className={`${sora.variable} ${cormorantGaramond.variable} ${manrope.variable} font-body antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* Synchronize store with server state to prevent hydration mismatch */}
          <ModeProvider initialMode={initialMode}>
            {children}
          </ModeProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
