export const contactFormCopy = {
  en: {
    name: 'Name',
    namePlaceholder: 'Your first name',
    surname: 'Surname',
    surnamePlaceholder: 'Your surname',
    email: 'Email',
    emailPlaceholder: 'contact@example.com',
    message: 'Message',
    commercialMessagePlaceholder: 'Tell us about your project…',
    weddingMessagePlaceholder: 'Tell us about your day…',
    weddingDate: 'Wedding Date',
    weddingDatePlaceholder: 'Pick a date',
    venue: 'Venue',
    venuePlaceholder: 'City, Country or Venue Name',
    submit: 'Send Message',
    sending: 'Sending...',
    unavailable:
      'Message sending is not available yet. Please use the contact details on this page.',
  },
  th: {
    name: 'ชื่อ',
    namePlaceholder: 'ชื่อของคุณ',
    surname: 'นามสกุล',
    surnamePlaceholder: 'นามสกุลของคุณ',
    email: 'อีเมล',
    emailPlaceholder: 'contact@example.com',
    message: 'ข้อความ',
    commercialMessagePlaceholder: 'เล่าให้เราฟังเกี่ยวกับโปรเจกต์ของคุณ…',
    weddingMessagePlaceholder: 'เล่าให้เราฟังเกี่ยวกับวันสำคัญของคุณ…',
    weddingDate: 'วันแต่งงาน',
    weddingDatePlaceholder: 'เลือกวันที่',
    venue: 'สถานที่จัดงาน',
    venuePlaceholder: 'เมือง ประเทศ หรือชื่อสถานที่จัดงาน',
    submit: 'ส่งข้อความ',
    sending: 'กำลังส่ง...',
    unavailable:
      'ขณะนี้ยังส่งข้อความผ่านฟอร์มไม่ได้ กรุณาติดต่อผ่านช่องทางที่แสดงในหน้านี้',
  },
} as const;
